// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace alamakota249031.Migrations
{
    [DbContext(typeof(RazorPagesGameContext))]
    [Migration("20210430164959_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("alamakota", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("string1")
                        .HasColumnType("TEXT");

                    b.Property<string>("string2")
                        .HasColumnType("TEXT");

                    b.Property<string>("stringSum")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("alamakota");
                });
#pragma warning restore 612, 618
        }
    }
}
